[package]
name = "glide-app"
description = "Mac-style smooth scrolling for Windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "glide"
path = "src/main.rs"

[dependencies]
glide-engine.workspace = true
glide-win.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.0.7"

[dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]
